
### SePay Webhook Test
POST http://localhost:4000/payments/webhook/sepay
Content-Type: application/json
Authorization: Apikey YOUR_SEPAY_API_KEY_HERE

{
    "id": 92710,
    "gateway": "Vietcombank",
    "transactionDate": "2023-03-25 14:02:37",
    "accountNumber": "0123499999",
    "code": null,
    "content": "PAY SEPAY_REF_CODE_HERE",
    "transferType": "in",
    "transferAmount": 2277000,
    "accumulated": 19077000,
    "subAccount": null,
    "referenceCode": "MBVCB.3278907687",
    "description": ""
}
