export enum CourseRunStatus {
    PLANNING = 'PLANNING',
    ENROLLING = 'ENROLLING',
    IN_PROGRESS = 'IN_PROGRESS',
    POSTPONED = 'POSTPONED',
    CANCELLED_BY_SYSTEM = 'CANCELLED_BY_SYSTEM',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
}
