export enum CourseRunStatus {
    DRAFT = 'DRAFT',
    PENDING_REVIEW = 'PENDING_REVIEW',
    CHANGES_REQUIRED = 'CHANGES_REQUIRED',
    APPROVED = 'APPROVED',
    PLANNING = 'PLANNING',
    ENROLLING = 'ENROLLING',
    IN_PROGRESS = 'IN_PROGRESS',
    POSTPONED = 'POSTPONED',
    CANCELLED_BY_SYSTEM = 'CANCELLED_BY_SYSTEM',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
    ARCHIVED = 'ARCHIVED',
}
