/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Ky9 Gateway API
 * The Gateway API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface Course {
  /** The unique identifier of the course */
  id: number;
  /** The title of the course */
  title: string;
  /** The description of the course */
  description?: string;
  /** The price of the course */
  price: number;
  /** Whether the course is published */
  published: boolean;
  /** The creation date of the course */
  createdAt: string;
  /** The last update date of the course */
  updatedAt: string;
}

export interface CreateCourseInput {
  /** The title of the new course */
  title: string;
  /** The description of the new course */
  description?: string;
  /** The price of the new course */
  price: number;
  /** Whether the new course is published */
  published?: boolean;
}

export interface UpdateCourseInput {
  /** The updated title of the course */
  title?: string;
  /** The updated description of the course */
  description?: string;
  /** The updated price of the course */
  price?: number;
  /** Whether the course is published */
  published?: boolean;
}

export const authControllerRegister = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `http://localhost:8080/api/auth/register`,undefined,options
    );
  }



export const getAuthControllerRegisterMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError,void, TContext> => {

const mutationKey = ['authControllerRegister'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRegister>>, void> = () => {
          

          return  authControllerRegister(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRegister>>>
    
    export type AuthControllerRegisterMutationError = AxiosError<unknown>

    export const useAuthControllerRegister = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRegister>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const authControllerLogin = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `http://localhost:8080/api/auth/login`,undefined,options
    );
  }



export const getAuthControllerLoginMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,void, TContext> => {

const mutationKey = ['authControllerLogin'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogin>>, void> = () => {
          

          return  authControllerLogin(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
    
    export type AuthControllerLoginMutationError = AxiosError<unknown>

    export const useAuthControllerLogin = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogin>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const authControllerLogout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `http://localhost:8080/api/auth/logout`,undefined,options
    );
  }



export const getAuthControllerLogoutMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext> => {

const mutationKey = ['authControllerLogout'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogout>>, void> = () => {
          

          return  authControllerLogout(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogout>>>
    
    export type AuthControllerLogoutMutationError = AxiosError<unknown>

    export const useAuthControllerLogout = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get all courses
 */
export const courseControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Course[]>> => {
    
    
    return axios.default.get(
      `http://localhost:8080/api/courses`,options
    );
  }




export const getCourseControllerFindAllQueryKey = () => {
    return [
    `http://localhost:8080/api/courses`
    ] as const;
    }

    
export const getCourseControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof courseControllerFindAll>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCourseControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof courseControllerFindAll>>> = ({ signal }) => courseControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CourseControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof courseControllerFindAll>>>
export type CourseControllerFindAllQueryError = AxiosError<unknown>


export function useCourseControllerFindAll<TData = Awaited<ReturnType<typeof courseControllerFindAll>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof courseControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof courseControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCourseControllerFindAll<TData = Awaited<ReturnType<typeof courseControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof courseControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof courseControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCourseControllerFindAll<TData = Awaited<ReturnType<typeof courseControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all courses
 */

export function useCourseControllerFindAll<TData = Awaited<ReturnType<typeof courseControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCourseControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create a new course
 */
export const courseControllerCreate = (
    createCourseInput: CreateCourseInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Course>> => {
    
    
    return axios.default.post(
      `http://localhost:8080/api/courses`,
      createCourseInput,options
    );
  }



export const getCourseControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof courseControllerCreate>>, TError,{data: CreateCourseInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof courseControllerCreate>>, TError,{data: CreateCourseInput}, TContext> => {

const mutationKey = ['courseControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof courseControllerCreate>>, {data: CreateCourseInput}> = (props) => {
          const {data} = props ?? {};

          return  courseControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CourseControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof courseControllerCreate>>>
    export type CourseControllerCreateMutationBody = CreateCourseInput
    export type CourseControllerCreateMutationError = AxiosError<unknown>

    /**
 * @summary Create a new course
 */
export const useCourseControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof courseControllerCreate>>, TError,{data: CreateCourseInput}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof courseControllerCreate>>,
        TError,
        {data: CreateCourseInput},
        TContext
      > => {

      const mutationOptions = getCourseControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get a course by id
 */
export const courseControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Course>> => {
    
    
    return axios.default.get(
      `http://localhost:8080/api/courses/${id}`,options
    );
  }




export const getCourseControllerFindOneQueryKey = (id?: string,) => {
    return [
    `http://localhost:8080/api/courses/${id}`
    ] as const;
    }

    
export const getCourseControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof courseControllerFindOne>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCourseControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof courseControllerFindOne>>> = ({ signal }) => courseControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CourseControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof courseControllerFindOne>>>
export type CourseControllerFindOneQueryError = AxiosError<unknown>


export function useCourseControllerFindOne<TData = Awaited<ReturnType<typeof courseControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof courseControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof courseControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCourseControllerFindOne<TData = Awaited<ReturnType<typeof courseControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof courseControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof courseControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCourseControllerFindOne<TData = Awaited<ReturnType<typeof courseControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a course by id
 */

export function useCourseControllerFindOne<TData = Awaited<ReturnType<typeof courseControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCourseControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Update a course
 */
export const courseControllerUpdate = (
    id: string,
    updateCourseInput: UpdateCourseInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Course>> => {
    
    
    return axios.default.patch(
      `http://localhost:8080/api/courses/${id}`,
      updateCourseInput,options
    );
  }



export const getCourseControllerUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof courseControllerUpdate>>, TError,{id: string;data: UpdateCourseInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof courseControllerUpdate>>, TError,{id: string;data: UpdateCourseInput}, TContext> => {

const mutationKey = ['courseControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof courseControllerUpdate>>, {id: string;data: UpdateCourseInput}> = (props) => {
          const {id,data} = props ?? {};

          return  courseControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CourseControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof courseControllerUpdate>>>
    export type CourseControllerUpdateMutationBody = UpdateCourseInput
    export type CourseControllerUpdateMutationError = AxiosError<unknown>

    /**
 * @summary Update a course
 */
export const useCourseControllerUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof courseControllerUpdate>>, TError,{id: string;data: UpdateCourseInput}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof courseControllerUpdate>>,
        TError,
        {id: string;data: UpdateCourseInput},
        TContext
      > => {

      const mutationOptions = getCourseControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Delete a course
 */
export const courseControllerDelete = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<boolean>> => {
    
    
    return axios.default.delete(
      `http://localhost:8080/api/courses/${id}`,options
    );
  }



export const getCourseControllerDeleteMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof courseControllerDelete>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof courseControllerDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['courseControllerDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof courseControllerDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  courseControllerDelete(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CourseControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof courseControllerDelete>>>
    
    export type CourseControllerDeleteMutationError = AxiosError<unknown>

    /**
 * @summary Delete a course
 */
export const useCourseControllerDelete = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof courseControllerDelete>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof courseControllerDelete>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getCourseControllerDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
