/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Ky9 Gateway API
 * The Gateway API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './axios-client';
export interface Course {
  /** The unique identifier of the course */
  id: number;
  /** The title of the course */
  title: string;
  /** The description of the course */
  description?: string;
  /** The price of the course */
  price: number;
  /** Whether the course is published */
  published: boolean;
  /** The creation date of the course */
  createdAt: string;
  /** The last update date of the course */
  updatedAt: string;
}

export interface CreateCourseInput {
  /** The title of the new course */
  title: string;
  /** The description of the new course */
  description?: string;
  /** The price of the new course */
  price: number;
  /** Whether the new course is published */
  published?: boolean;
}

export interface UpdateCourseInput {
  /** The updated title of the course */
  title?: string;
  /** The updated description of the course */
  description?: string;
  /** The updated price of the course */
  price?: number;
  /** Whether the course is published */
  published?: boolean;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const authControllerRegister = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/auth/register`, method: 'POST', signal
    },
      options);
    }
  


export const getAuthControllerRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError,void, TContext> => {

const mutationKey = ['authControllerRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRegister>>, void> = () => {
          

          return  authControllerRegister(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRegister>>>
    
    export type AuthControllerRegisterMutationError = unknown

    export const useAuthControllerRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRegister>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerRegisterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const authControllerLogin = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/auth/login`, method: 'POST', signal
    },
      options);
    }
  


export const getAuthControllerLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,void, TContext> => {

const mutationKey = ['authControllerLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogin>>, void> = () => {
          

          return  authControllerLogin(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
    
    export type AuthControllerLoginMutationError = unknown

    export const useAuthControllerLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogin>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerLoginMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const authControllerLogout = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/auth/logout`, method: 'POST', signal
    },
      options);
    }
  


export const getAuthControllerLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext> => {

const mutationKey = ['authControllerLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogout>>, void> = () => {
          

          return  authControllerLogout(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogout>>>
    
    export type AuthControllerLogoutMutationError = unknown

    export const useAuthControllerLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerLogoutMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get all courses
 */
export const courseControllerFindAll = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Course[]>(
      {url: `/api/courses`, method: 'GET', signal
    },
      options);
    }
  



export const getCourseControllerFindAllQueryKey = () => {
    return [
    `/api/courses`
    ] as const;
    }

    
export const getCourseControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof courseControllerFindAll>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCourseControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof courseControllerFindAll>>> = ({ signal }) => courseControllerFindAll(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type CourseControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof courseControllerFindAll>>>
export type CourseControllerFindAllQueryError = unknown


/**
 * @summary Get all courses
 */

export function useCourseControllerFindAll<TData = Awaited<ReturnType<typeof courseControllerFindAll>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCourseControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create a new course
 */
export const courseControllerCreate = (
    createCourseInput: CreateCourseInput,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Course>(
      {url: `/api/courses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCourseInput, signal
    },
      options);
    }
  


export const getCourseControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof courseControllerCreate>>, TError,{data: CreateCourseInput}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof courseControllerCreate>>, TError,{data: CreateCourseInput}, TContext> => {

const mutationKey = ['courseControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof courseControllerCreate>>, {data: CreateCourseInput}> = (props) => {
          const {data} = props ?? {};

          return  courseControllerCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CourseControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof courseControllerCreate>>>
    export type CourseControllerCreateMutationBody = CreateCourseInput
    export type CourseControllerCreateMutationError = unknown

    /**
 * @summary Create a new course
 */
export const useCourseControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof courseControllerCreate>>, TError,{data: CreateCourseInput}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof courseControllerCreate>>,
        TError,
        {data: CreateCourseInput},
        TContext
      > => {

      const mutationOptions = getCourseControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get a course by id
 */
export const courseControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Course>(
      {url: `/api/courses/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getCourseControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/api/courses/${id}`
    ] as const;
    }

    
export const getCourseControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof courseControllerFindOne>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindOne>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCourseControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof courseControllerFindOne>>> = ({ signal }) => courseControllerFindOne(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type CourseControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof courseControllerFindOne>>>
export type CourseControllerFindOneQueryError = unknown


/**
 * @summary Get a course by id
 */

export function useCourseControllerFindOne<TData = Awaited<ReturnType<typeof courseControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof courseControllerFindOne>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCourseControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Update a course
 */
export const courseControllerUpdate = (
    id: string,
    updateCourseInput: UpdateCourseInput,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Course>(
      {url: `/api/courses/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateCourseInput
    },
      options);
    }
  


export const getCourseControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof courseControllerUpdate>>, TError,{id: string;data: UpdateCourseInput}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof courseControllerUpdate>>, TError,{id: string;data: UpdateCourseInput}, TContext> => {

const mutationKey = ['courseControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof courseControllerUpdate>>, {id: string;data: UpdateCourseInput}> = (props) => {
          const {id,data} = props ?? {};

          return  courseControllerUpdate(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CourseControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof courseControllerUpdate>>>
    export type CourseControllerUpdateMutationBody = UpdateCourseInput
    export type CourseControllerUpdateMutationError = unknown

    /**
 * @summary Update a course
 */
export const useCourseControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof courseControllerUpdate>>, TError,{id: string;data: UpdateCourseInput}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof courseControllerUpdate>>,
        TError,
        {id: string;data: UpdateCourseInput},
        TContext
      > => {

      const mutationOptions = getCourseControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Delete a course
 */
export const courseControllerDelete = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<boolean>(
      {url: `/api/courses/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getCourseControllerDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof courseControllerDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof courseControllerDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['courseControllerDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof courseControllerDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  courseControllerDelete(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CourseControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof courseControllerDelete>>>
    
    export type CourseControllerDeleteMutationError = unknown

    /**
 * @summary Delete a course
 */
export const useCourseControllerDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof courseControllerDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof courseControllerDelete>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getCourseControllerDeleteMutationOptions(options);

      return useMutation(mutationOptions);
    }
